name: Check format
on:
  pull_request:
    branches: 
    - master 
    - develop
jobs:
  check_translation:
    name: Check format
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Setup python3
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Run check_translation for pull_request
      run: |
        import os
        from linter.test import check_translation_format

        check_translation_format(os.environ['GITHUB_BASE_REF'])
      shell: python 